### Numpy

In [1]:
import numpy as np

In [8]:
data1 = [3,5.5,4,7,8,9]
arr1 = np.array(data1)
arr1

array([3. , 5.5, 4. , 7. , 8. , 9. ])

In [9]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [12]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [15]:
 print(np.zeros((3, 6)))    # 6개의 0으로 구성된 리스트 3개
 print(np.empty((2, 3, 2))) # 2개의 초기화되지 않은 값으로 채워진 배열을 가진 리스트 3개를 가진 리스트를 2개 생성

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.02360256e-306]
  [1.33511018e-306 1.33511969e-306]]

 [[6.23037996e-307 6.23053954e-307]
  [1.78021527e-306 1.24611266e-306]
  [9.34598925e-307 8.34446411e-308]]]


In [16]:
 np.arange(20) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [22]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names == 'Bob')
print(names != 'Bob')

[ True False False  True False False False]
[False  True  True False  True  True  True]


In [48]:
data = np.random.randn(7,4)
print(data)
print('----')
print(data[names=='Bob'])

[[ 0.14930564 -0.55857098 -0.44290398 -0.94805958]
 [ 0.71407601  0.41383503  0.61914973  1.46344251]
 [-0.38162627  0.54156523 -0.30974501 -1.78464686]
 [-0.70666686 -0.03160979  1.88737329 -1.73356373]
 [ 0.6145351   1.12508607 -0.7796303   1.20448465]
 [-0.17339689  0.88269531 -0.12439104  0.52407935]
 [-0.28859691 -1.64174176 -0.49308522 -0.93343962]]
----
[[ 0.14930564 -0.55857098 -0.44290398 -0.94805958]
 [-0.70666686 -0.03160979  1.88737329 -1.73356373]]


In [65]:
arr = np.empty((8, 4))
print(arr)

print('-'*20)

for i in range(8):
    arr[i] = i
print(arr)

print('-'*20)

print(arr[1,3])

print('-'*20)

print(arr[[1,3,2]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
--------------------
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
--------------------
1.0
--------------------
[[1. 1. 1. 1.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]]


In [74]:
arr = np.arange(32).reshape((8,4))
print(arr)

print('-'*20)

print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

print('-'*20)

print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
--------------------
[ 4 23 29 10]
--------------------
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [76]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [80]:
arr = np.arange(15).reshape((3, 5))
print(arr)

print('-'*20)

print(arr.T) # Transpose

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
